version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
  web:
    build: .
    ports:
      - '5173:5173'
    environment:
      - PAYLOAD_SECRET=secret
      - PAYLOAD_MONGODB_URI=mongodb://mongo:27017/payload
      - VITE_TRPC=http://localhost:5173/trpc
    depends_on:
      - mongo
    # networks:
    #   - traefik
    # labels:
    #   - 'traefik.enable=true'
    #   - 'traefik.http.routers.sveltekitstarter.rule=Host(`web.docker.localhost`)'
    #   - 'traefik.http.routers.sveltekitstarter.entrypoints=websecure'
    #   - 'traefik.http.routers.sveltekitstarter.tls.certresolver=letsencrypt'
# networks:
#   traefik:
#     external: true

volumes:
  data:
  node_modules:
