version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - db:/data/db
  web:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    # networks:
    #   - traefik
    # labels:
    #   - 'traefik.enable=true'
    #   - 'traefik.http.routers.sveltekitstarter.rule=Host(`web.docker.localhost`)'
    #   - 'traefik.http.routers.sveltekitstarter.entrypoints=websecure'
    #   - 'traefik.http.routers.sveltekitstarter.tls.certresolver=letsencrypt'
# networks:
#   traefik:
#     external: true

volumes:
  db:
